// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_UNKNOWN           EventType = 0
	EventType_EVENT_SESSION_NEW       EventType = 1
	EventType_EVENT_SESSION_LOST      EventType = 2
	EventType_EVENT_TASK_RESULT       EventType = 3
	EventType_EVENT_LOG               EventType = 4
	EventType_EVENT_APPROVAL_REQUIRED EventType = 5
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_SESSION_NEW",
		2: "EVENT_SESSION_LOST",
		3: "EVENT_TASK_RESULT",
		4: "EVENT_LOG",
		5: "EVENT_APPROVAL_REQUIRED",
	}
	EventType_value = map[string]int32{
		"EVENT_UNKNOWN":           0,
		"EVENT_SESSION_NEW":       1,
		"EVENT_SESSION_LOST":      2,
		"EVENT_TASK_RESULT":       3,
		"EVENT_LOG":               4,
		"EVENT_APPROVAL_REQUIRED": 5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type SessionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ImplantId      string                 `protobuf:"bytes,2,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username       string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Os             string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	Pid            uint32                 `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	IntegrityLevel string                 `protobuf:"bytes,8,opt,name=integrity_level,json=integrityLevel,proto3" json:"integrity_level,omitempty"`
	Transport      string                 `protobuf:"bytes,9,opt,name=transport,proto3" json:"transport,omitempty"`
	RemoteAddr     string                 `protobuf:"bytes,10,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	RegisteredAt   int64                  `protobuf:"varint,11,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastCheckin    int64                  `protobuf:"varint,12,opt,name=last_checkin,json=lastCheckin,proto3" json:"last_checkin,omitempty"`
	Alive          bool                   `protobuf:"varint,13,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *SessionInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SessionInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SessionInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SessionInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SessionInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionInfo) GetIntegrityLevel() string {
	if x != nil {
		return x.IntegrityLevel
	}
	return ""
}

func (x *SessionInfo) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *SessionInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *SessionInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *SessionInfo) GetLastCheckin() int64 {
	if x != nil {
		return x.LastCheckin
	}
	return 0
}

func (x *SessionInfo) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type StartListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ListenerConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartListenerRequest) Reset() {
	*x = StartListenerRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerRequest) ProtoMessage() {}

func (x *StartListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerRequest.ProtoReflect.Descriptor instead.
func (*StartListenerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *StartListenerRequest) GetConfig() *ListenerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type StartListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Status        *ListenerStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartListenerResponse) Reset() {
	*x = StartListenerResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerResponse) ProtoMessage() {}

func (x *StartListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerResponse.ProtoReflect.Descriptor instead.
func (*StartListenerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *StartListenerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartListenerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StartListenerResponse) GetStatus() *ListenerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopListenerRequest) Reset() {
	*x = StopListenerRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerRequest) ProtoMessage() {}

func (x *StopListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerRequest.ProtoReflect.Descriptor instead.
func (*StopListenerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *StopListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopListenerResponse) Reset() {
	*x = StopListenerResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerResponse) ProtoMessage() {}

func (x *StopListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerResponse.ProtoReflect.Descriptor instead.
func (*StopListenerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *StopListenerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopListenerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListListenersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListenersRequest) Reset() {
	*x = ListListenersRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListenersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListenersRequest) ProtoMessage() {}

func (x *ListListenersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListenersRequest.ProtoReflect.Descriptor instead.
func (*ListListenersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

type ListListenersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listeners     []*ListenerStatus      `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListenersResponse) Reset() {
	*x = ListListenersResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListenersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListenersResponse) ProtoMessage() {}

func (x *ListListenersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListenersResponse.ProtoReflect.Descriptor instead.
func (*ListListenersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListListenersResponse) GetListeners() []*ListenerStatus {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionInfo           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetSessionResponse) GetSession() *SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *KillSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionResponse) Reset() {
	*x = KillSessionResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionResponse) ProtoMessage() {}

func (x *KillSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionResponse.ProtoReflect.Descriptor instead.
func (*KillSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *KillSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=erebus.c2.TaskType" json:"task_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Wait          bool                   `protobuf:"varint,5,opt,name=wait,proto3" json:"wait,omitempty"` // Block until result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_UNKNOWN
}

func (x *ExecuteTaskRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecuteTaskRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecuteTaskRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type ExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        *TaskResult            `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Populated only if wait=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskResponse) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetTaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultRequest) Reset() {
	*x = GetTaskResultRequest{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultRequest) ProtoMessage() {}

func (x *GetTaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TaskResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Pending       bool                   `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultResponse) Reset() {
	*x = GetTaskResultResponse{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultResponse) ProtoMessage() {}

func (x *GetTaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetTaskResultResponse) GetResult() *TaskResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTaskResultResponse) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *ListTasksRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ApprovalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	TaskType        TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=erebus.c2.TaskType" json:"task_type,omitempty"`
	RiskLevel       string                 `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RequestedAt     int64                  `protobuf:"varint,6,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *ApprovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApprovalRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *ApprovalRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_UNKNOWN
}

func (x *ApprovalRequest) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ApprovalRequest) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *ApproveRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *ApproveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DenyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyRequest) Reset() {
	*x = DenyRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyRequest) ProtoMessage() {}

func (x *DenyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyRequest.ProtoReflect.Descriptor instead.
func (*DenyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *DenyRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *DenyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyResponse) Reset() {
	*x = DenyResponse{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyResponse) ProtoMessage() {}

func (x *DenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyResponse.ProtoReflect.Descriptor instead.
func (*DenyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *DenyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPendingApprovalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsRequest) Reset() {
	*x = ListPendingApprovalsRequest{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsRequest) ProtoMessage() {}

func (x *ListPendingApprovalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

type ListPendingApprovalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approvals     []*ApprovalRequest     `protobuf:"bytes,1,rep,name=approvals,proto3" json:"approvals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingApprovalsResponse) Reset() {
	*x = ListPendingApprovalsResponse{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingApprovalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingApprovalsResponse) ProtoMessage() {}

func (x *ListPendingApprovalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingApprovalsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingApprovalsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *ListPendingApprovalsResponse) GetApprovals() []*ApprovalRequest {
	if x != nil {
		return x.Approvals
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=erebus.c2.EventType" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNKNOWN
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

type GenerateImplantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Transport     string                 `protobuf:"bytes,3,opt,name=transport,proto3" json:"transport,omitempty"`
	Callbacks     []string               `protobuf:"bytes,4,rep,name=callbacks,proto3" json:"callbacks,omitempty"`
	SleepMs       int64                  `protobuf:"varint,5,opt,name=sleep_ms,json=sleepMs,proto3" json:"sleep_ms,omitempty"`
	JitterPct     int32                  `protobuf:"varint,6,opt,name=jitter_pct,json=jitterPct,proto3" json:"jitter_pct,omitempty"`
	Garble        bool                   `protobuf:"varint,7,opt,name=garble,proto3" json:"garble,omitempty"`
	CdnDomain     string                 `protobuf:"bytes,8,opt,name=cdn_domain,json=cdnDomain,proto3" json:"cdn_domain,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`                         // "exe" (default), "shellcode", "dll"
	DnsDomain     string                 `protobuf:"bytes,10,opt,name=dns_domain,json=dnsDomain,proto3" json:"dns_domain,omitempty"` // DNS C2 zone (required when transport=dns)
	DnsServer     string                 `protobuf:"bytes,11,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"` // DNS resolver host:port
	Language      string                 `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`                    // "go" (default), "c"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImplantRequest) Reset() {
	*x = GenerateImplantRequest{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImplantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImplantRequest) ProtoMessage() {}

func (x *GenerateImplantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImplantRequest.ProtoReflect.Descriptor instead.
func (*GenerateImplantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *GenerateImplantRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GenerateImplantRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *GenerateImplantRequest) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *GenerateImplantRequest) GetCallbacks() []string {
	if x != nil {
		return x.Callbacks
	}
	return nil
}

func (x *GenerateImplantRequest) GetSleepMs() int64 {
	if x != nil {
		return x.SleepMs
	}
	return 0
}

func (x *GenerateImplantRequest) GetJitterPct() int32 {
	if x != nil {
		return x.JitterPct
	}
	return 0
}

func (x *GenerateImplantRequest) GetGarble() bool {
	if x != nil {
		return x.Garble
	}
	return false
}

func (x *GenerateImplantRequest) GetCdnDomain() string {
	if x != nil {
		return x.CdnDomain
	}
	return ""
}

func (x *GenerateImplantRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GenerateImplantRequest) GetDnsDomain() string {
	if x != nil {
		return x.DnsDomain
	}
	return ""
}

func (x *GenerateImplantRequest) GetDnsServer() string {
	if x != nil {
		return x.DnsServer
	}
	return ""
}

func (x *GenerateImplantRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GenerateImplantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	BuildId       string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Binary        []byte                 `protobuf:"bytes,4,opt,name=binary,proto3" json:"binary,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImplantResponse) Reset() {
	*x = GenerateImplantResponse{}
	mi := &file_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImplantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImplantResponse) ProtoMessage() {}

func (x *GenerateImplantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImplantResponse.ProtoReflect.Descriptor instead.
func (*GenerateImplantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{29}
}

func (x *GenerateImplantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateImplantResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GenerateImplantResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *GenerateImplantResponse) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *GenerateImplantResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GenerateImplantResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type LootItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootItem) Reset() {
	*x = LootItem{}
	mi := &file_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootItem) ProtoMessage() {}

func (x *LootItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootItem.ProtoReflect.Descriptor instead.
func (*LootItem) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{30}
}

func (x *LootItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LootItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LootItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LootItem) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LootItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LootItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListLootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLootRequest) Reset() {
	*x = ListLootRequest{}
	mi := &file_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLootRequest) ProtoMessage() {}

func (x *ListLootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLootRequest.ProtoReflect.Descriptor instead.
func (*ListLootRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{31}
}

func (x *ListLootRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListLootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LootItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLootResponse) Reset() {
	*x = ListLootResponse{}
	mi := &file_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLootResponse) ProtoMessage() {}

func (x *ListLootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLootResponse.ProtoReflect.Descriptor instead.
func (*ListLootResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{32}
}

func (x *ListLootResponse) GetItems() []*LootItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetLootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLootRequest) Reset() {
	*x = GetLootRequest{}
	mi := &file_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLootRequest) ProtoMessage() {}

func (x *GetLootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLootRequest.ProtoReflect.Descriptor instead.
func (*GetLootRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{33}
}

func (x *GetLootRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *LootItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLootResponse) Reset() {
	*x = GetLootResponse{}
	mi := &file_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLootResponse) ProtoMessage() {}

func (x *GetLootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLootResponse.ProtoReflect.Descriptor instead.
func (*GetLootResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{34}
}

func (x *GetLootResponse) GetItem() *LootItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\terebus.c2\x1a\bc2.proto\x1a\x0elistener.proto\"\xff\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x02 \x01(\tR\timplantId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12\x10\n" +
	"\x03pid\x18\a \x01(\rR\x03pid\x12'\n" +
	"\x0fintegrity_level\x18\b \x01(\tR\x0eintegrityLevel\x12\x1c\n" +
	"\ttransport\x18\t \x01(\tR\ttransport\x12\x1f\n" +
	"\vremote_addr\x18\n" +
	" \x01(\tR\n" +
	"remoteAddr\x12#\n" +
	"\rregistered_at\x18\v \x01(\x03R\fregisteredAt\x12!\n" +
	"\flast_checkin\x18\f \x01(\x03R\vlastCheckin\x12\x14\n" +
	"\x05alive\x18\r \x01(\bR\x05alive\"I\n" +
	"\x14StartListenerRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.erebus.c2.ListenerConfigR\x06config\"z\n" +
	"\x15StartListenerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x19.erebus.c2.ListenerStatusR\x06status\"%\n" +
	"\x13StopListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x14StopListenerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x16\n" +
	"\x14ListListenersRequest\"P\n" +
	"\x15ListListenersResponse\x127\n" +
	"\tlisteners\x18\x01 \x03(\v2\x19.erebus.c2.ListenerStatusR\tlisteners\"\x15\n" +
	"\x13ListSessionsRequest\"J\n" +
	"\x14ListSessionsResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.erebus.c2.SessionInfoR\bsessions\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"F\n" +
	"\x12GetSessionResponse\x120\n" +
	"\asession\x18\x01 \x01(\v2\x16.erebus.c2.SessionInfoR\asession\"3\n" +
	"\x12KillSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"E\n" +
	"\x13KillSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xac\x01\n" +
	"\x12ExecuteTaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x13.erebus.c2.TaskTypeR\btaskType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12\x12\n" +
	"\x04wait\x18\x05 \x01(\bR\x04wait\"]\n" +
	"\x13ExecuteTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x06result\x18\x02 \x01(\v2\x15.erebus.c2.TaskResultR\x06result\"/\n" +
	"\x14GetTaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"`\n" +
	"\x15GetTaskResultResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.erebus.c2.TaskResultR\x06result\x12\x18\n" +
	"\apending\x18\x02 \x01(\bR\apending\"1\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\":\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.erebus.c2.TaskR\x05tasks\"\xdf\x01\n" +
	"\x0fApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x120\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\x13.erebus.c2.TaskTypeR\btaskType\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\tR\triskLevel\x12!\n" +
	"\frequested_at\x18\x06 \x01(\x03R\vrequestedAt\"1\n" +
	"\x0eApproveRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\"+\n" +
	"\x0fApproveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\vDenyRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"(\n" +
	"\fDenyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1d\n" +
	"\x1bListPendingApprovalsRequest\"X\n" +
	"\x1cListPendingApprovalsResponse\x128\n" +
	"\tapprovals\x18\x01 \x03(\v2\x1a.erebus.c2.ApprovalRequestR\tapprovals\"\xb5\x01\n" +
	"\x05Event\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.erebus.c2.EventTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\x12\n" +
	"\x10SubscribeRequest\"\xdb\x02\n" +
	"\x16GenerateImplantRequest\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1c\n" +
	"\ttransport\x18\x03 \x01(\tR\ttransport\x12\x1c\n" +
	"\tcallbacks\x18\x04 \x03(\tR\tcallbacks\x12\x19\n" +
	"\bsleep_ms\x18\x05 \x01(\x03R\asleepMs\x12\x1d\n" +
	"\n" +
	"jitter_pct\x18\x06 \x01(\x05R\tjitterPct\x12\x16\n" +
	"\x06garble\x18\a \x01(\bR\x06garble\x12\x1d\n" +
	"\n" +
	"cdn_domain\x18\b \x01(\tR\tcdnDomain\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"dns_domain\x18\n" +
	" \x01(\tR\tdnsDomain\x12\x1d\n" +
	"\n" +
	"dns_server\x18\v \x01(\tR\tdnsServer\x12\x1a\n" +
	"\blanguage\x18\f \x01(\tR\blanguage\"\xb0\x01\n" +
	"\x17GenerateImplantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12\x16\n" +
	"\x06binary\x18\x04 \x01(\fR\x06binary\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"\x98\x01\n" +
	"\bLootItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"0\n" +
	"\x0fListLootRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"=\n" +
	"\x10ListLootResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.erebus.c2.LootItemR\x05items\" \n" +
	"\x0eGetLootRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fGetLootResponse\x12'\n" +
	"\x04item\x18\x01 \x01(\v2\x13.erebus.c2.LootItemR\x04item*\x90\x01\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11EVENT_SESSION_NEW\x10\x01\x12\x16\n" +
	"\x12EVENT_SESSION_LOST\x10\x02\x12\x15\n" +
	"\x11EVENT_TASK_RESULT\x10\x03\x12\r\n" +
	"\tEVENT_LOG\x10\x04\x12\x1b\n" +
	"\x17EVENT_APPROVAL_REQUIRED\x10\x052\xda\t\n" +
	"\bErebusC2\x12R\n" +
	"\rStartListener\x12\x1f.erebus.c2.StartListenerRequest\x1a .erebus.c2.StartListenerResponse\x12O\n" +
	"\fStopListener\x12\x1e.erebus.c2.StopListenerRequest\x1a\x1f.erebus.c2.StopListenerResponse\x12R\n" +
	"\rListListeners\x12\x1f.erebus.c2.ListListenersRequest\x1a .erebus.c2.ListListenersResponse\x12O\n" +
	"\fListSessions\x12\x1e.erebus.c2.ListSessionsRequest\x1a\x1f.erebus.c2.ListSessionsResponse\x12I\n" +
	"\n" +
	"GetSession\x12\x1c.erebus.c2.GetSessionRequest\x1a\x1d.erebus.c2.GetSessionResponse\x12L\n" +
	"\vKillSession\x12\x1d.erebus.c2.KillSessionRequest\x1a\x1e.erebus.c2.KillSessionResponse\x12L\n" +
	"\vExecuteTask\x12\x1d.erebus.c2.ExecuteTaskRequest\x1a\x1e.erebus.c2.ExecuteTaskResponse\x12R\n" +
	"\rGetTaskResult\x12\x1f.erebus.c2.GetTaskResultRequest\x1a .erebus.c2.GetTaskResultResponse\x12F\n" +
	"\tListTasks\x12\x1b.erebus.c2.ListTasksRequest\x1a\x1c.erebus.c2.ListTasksResponse\x12<\n" +
	"\tSubscribe\x12\x1b.erebus.c2.SubscribeRequest\x1a\x10.erebus.c2.Event0\x01\x12X\n" +
	"\x0fGenerateImplant\x12!.erebus.c2.GenerateImplantRequest\x1a\".erebus.c2.GenerateImplantResponse\x12C\n" +
	"\bListLoot\x12\x1a.erebus.c2.ListLootRequest\x1a\x1b.erebus.c2.ListLootResponse\x12@\n" +
	"\aGetLoot\x12\x19.erebus.c2.GetLootRequest\x1a\x1a.erebus.c2.GetLootResponse\x12g\n" +
	"\x14ListPendingApprovals\x12&.erebus.c2.ListPendingApprovalsRequest\x1a'.erebus.c2.ListPendingApprovalsResponse\x12@\n" +
	"\aApprove\x12\x19.erebus.c2.ApproveRequest\x1a\x1a.erebus.c2.ApproveResponse\x127\n" +
	"\x04Deny\x12\x16.erebus.c2.DenyRequest\x1a\x17.erebus.c2.DenyResponseB5Z3github.com/KKingZero/erebus-exploit-framwork/pkg/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_proto_goTypes = []any{
	(EventType)(0),                       // 0: erebus.c2.EventType
	(*SessionInfo)(nil),                  // 1: erebus.c2.SessionInfo
	(*StartListenerRequest)(nil),         // 2: erebus.c2.StartListenerRequest
	(*StartListenerResponse)(nil),        // 3: erebus.c2.StartListenerResponse
	(*StopListenerRequest)(nil),          // 4: erebus.c2.StopListenerRequest
	(*StopListenerResponse)(nil),         // 5: erebus.c2.StopListenerResponse
	(*ListListenersRequest)(nil),         // 6: erebus.c2.ListListenersRequest
	(*ListListenersResponse)(nil),        // 7: erebus.c2.ListListenersResponse
	(*ListSessionsRequest)(nil),          // 8: erebus.c2.ListSessionsRequest
	(*ListSessionsResponse)(nil),         // 9: erebus.c2.ListSessionsResponse
	(*GetSessionRequest)(nil),            // 10: erebus.c2.GetSessionRequest
	(*GetSessionResponse)(nil),           // 11: erebus.c2.GetSessionResponse
	(*KillSessionRequest)(nil),           // 12: erebus.c2.KillSessionRequest
	(*KillSessionResponse)(nil),          // 13: erebus.c2.KillSessionResponse
	(*ExecuteTaskRequest)(nil),           // 14: erebus.c2.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),          // 15: erebus.c2.ExecuteTaskResponse
	(*GetTaskResultRequest)(nil),         // 16: erebus.c2.GetTaskResultRequest
	(*GetTaskResultResponse)(nil),        // 17: erebus.c2.GetTaskResultResponse
	(*ListTasksRequest)(nil),             // 18: erebus.c2.ListTasksRequest
	(*ListTasksResponse)(nil),            // 19: erebus.c2.ListTasksResponse
	(*ApprovalRequest)(nil),              // 20: erebus.c2.ApprovalRequest
	(*ApproveRequest)(nil),               // 21: erebus.c2.ApproveRequest
	(*ApproveResponse)(nil),              // 22: erebus.c2.ApproveResponse
	(*DenyRequest)(nil),                  // 23: erebus.c2.DenyRequest
	(*DenyResponse)(nil),                 // 24: erebus.c2.DenyResponse
	(*ListPendingApprovalsRequest)(nil),  // 25: erebus.c2.ListPendingApprovalsRequest
	(*ListPendingApprovalsResponse)(nil), // 26: erebus.c2.ListPendingApprovalsResponse
	(*Event)(nil),                        // 27: erebus.c2.Event
	(*SubscribeRequest)(nil),             // 28: erebus.c2.SubscribeRequest
	(*GenerateImplantRequest)(nil),       // 29: erebus.c2.GenerateImplantRequest
	(*GenerateImplantResponse)(nil),      // 30: erebus.c2.GenerateImplantResponse
	(*LootItem)(nil),                     // 31: erebus.c2.LootItem
	(*ListLootRequest)(nil),              // 32: erebus.c2.ListLootRequest
	(*ListLootResponse)(nil),             // 33: erebus.c2.ListLootResponse
	(*GetLootRequest)(nil),               // 34: erebus.c2.GetLootRequest
	(*GetLootResponse)(nil),              // 35: erebus.c2.GetLootResponse
	(*ListenerConfig)(nil),               // 36: erebus.c2.ListenerConfig
	(*ListenerStatus)(nil),               // 37: erebus.c2.ListenerStatus
	(TaskType)(0),                        // 38: erebus.c2.TaskType
	(*TaskResult)(nil),                   // 39: erebus.c2.TaskResult
	(*Task)(nil),                         // 40: erebus.c2.Task
}
var file_api_proto_depIdxs = []int32{
	36, // 0: erebus.c2.StartListenerRequest.config:type_name -> erebus.c2.ListenerConfig
	37, // 1: erebus.c2.StartListenerResponse.status:type_name -> erebus.c2.ListenerStatus
	37, // 2: erebus.c2.ListListenersResponse.listeners:type_name -> erebus.c2.ListenerStatus
	1,  // 3: erebus.c2.ListSessionsResponse.sessions:type_name -> erebus.c2.SessionInfo
	1,  // 4: erebus.c2.GetSessionResponse.session:type_name -> erebus.c2.SessionInfo
	38, // 5: erebus.c2.ExecuteTaskRequest.task_type:type_name -> erebus.c2.TaskType
	39, // 6: erebus.c2.ExecuteTaskResponse.result:type_name -> erebus.c2.TaskResult
	39, // 7: erebus.c2.GetTaskResultResponse.result:type_name -> erebus.c2.TaskResult
	40, // 8: erebus.c2.ListTasksResponse.tasks:type_name -> erebus.c2.Task
	38, // 9: erebus.c2.ApprovalRequest.task_type:type_name -> erebus.c2.TaskType
	20, // 10: erebus.c2.ListPendingApprovalsResponse.approvals:type_name -> erebus.c2.ApprovalRequest
	0,  // 11: erebus.c2.Event.type:type_name -> erebus.c2.EventType
	31, // 12: erebus.c2.ListLootResponse.items:type_name -> erebus.c2.LootItem
	31, // 13: erebus.c2.GetLootResponse.item:type_name -> erebus.c2.LootItem
	2,  // 14: erebus.c2.ErebusC2.StartListener:input_type -> erebus.c2.StartListenerRequest
	4,  // 15: erebus.c2.ErebusC2.StopListener:input_type -> erebus.c2.StopListenerRequest
	6,  // 16: erebus.c2.ErebusC2.ListListeners:input_type -> erebus.c2.ListListenersRequest
	8,  // 17: erebus.c2.ErebusC2.ListSessions:input_type -> erebus.c2.ListSessionsRequest
	10, // 18: erebus.c2.ErebusC2.GetSession:input_type -> erebus.c2.GetSessionRequest
	12, // 19: erebus.c2.ErebusC2.KillSession:input_type -> erebus.c2.KillSessionRequest
	14, // 20: erebus.c2.ErebusC2.ExecuteTask:input_type -> erebus.c2.ExecuteTaskRequest
	16, // 21: erebus.c2.ErebusC2.GetTaskResult:input_type -> erebus.c2.GetTaskResultRequest
	18, // 22: erebus.c2.ErebusC2.ListTasks:input_type -> erebus.c2.ListTasksRequest
	28, // 23: erebus.c2.ErebusC2.Subscribe:input_type -> erebus.c2.SubscribeRequest
	29, // 24: erebus.c2.ErebusC2.GenerateImplant:input_type -> erebus.c2.GenerateImplantRequest
	32, // 25: erebus.c2.ErebusC2.ListLoot:input_type -> erebus.c2.ListLootRequest
	34, // 26: erebus.c2.ErebusC2.GetLoot:input_type -> erebus.c2.GetLootRequest
	25, // 27: erebus.c2.ErebusC2.ListPendingApprovals:input_type -> erebus.c2.ListPendingApprovalsRequest
	21, // 28: erebus.c2.ErebusC2.Approve:input_type -> erebus.c2.ApproveRequest
	23, // 29: erebus.c2.ErebusC2.Deny:input_type -> erebus.c2.DenyRequest
	3,  // 30: erebus.c2.ErebusC2.StartListener:output_type -> erebus.c2.StartListenerResponse
	5,  // 31: erebus.c2.ErebusC2.StopListener:output_type -> erebus.c2.StopListenerResponse
	7,  // 32: erebus.c2.ErebusC2.ListListeners:output_type -> erebus.c2.ListListenersResponse
	9,  // 33: erebus.c2.ErebusC2.ListSessions:output_type -> erebus.c2.ListSessionsResponse
	11, // 34: erebus.c2.ErebusC2.GetSession:output_type -> erebus.c2.GetSessionResponse
	13, // 35: erebus.c2.ErebusC2.KillSession:output_type -> erebus.c2.KillSessionResponse
	15, // 36: erebus.c2.ErebusC2.ExecuteTask:output_type -> erebus.c2.ExecuteTaskResponse
	17, // 37: erebus.c2.ErebusC2.GetTaskResult:output_type -> erebus.c2.GetTaskResultResponse
	19, // 38: erebus.c2.ErebusC2.ListTasks:output_type -> erebus.c2.ListTasksResponse
	27, // 39: erebus.c2.ErebusC2.Subscribe:output_type -> erebus.c2.Event
	30, // 40: erebus.c2.ErebusC2.GenerateImplant:output_type -> erebus.c2.GenerateImplantResponse
	33, // 41: erebus.c2.ErebusC2.ListLoot:output_type -> erebus.c2.ListLootResponse
	35, // 42: erebus.c2.ErebusC2.GetLoot:output_type -> erebus.c2.GetLootResponse
	26, // 43: erebus.c2.ErebusC2.ListPendingApprovals:output_type -> erebus.c2.ListPendingApprovalsResponse
	22, // 44: erebus.c2.ErebusC2.Approve:output_type -> erebus.c2.ApproveResponse
	24, // 45: erebus.c2.ErebusC2.Deny:output_type -> erebus.c2.DenyResponse
	30, // [30:46] is the sub-list for method output_type
	14, // [14:30] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_c2_proto_init()
	file_listener_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
