// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ErebusC2_StartListener_FullMethodName         = "/erebus.c2.ErebusC2/StartListener"
	ErebusC2_StopListener_FullMethodName          = "/erebus.c2.ErebusC2/StopListener"
	ErebusC2_ListListeners_FullMethodName         = "/erebus.c2.ErebusC2/ListListeners"
	ErebusC2_ListSessions_FullMethodName          = "/erebus.c2.ErebusC2/ListSessions"
	ErebusC2_GetSession_FullMethodName            = "/erebus.c2.ErebusC2/GetSession"
	ErebusC2_KillSession_FullMethodName           = "/erebus.c2.ErebusC2/KillSession"
	ErebusC2_ExecuteTask_FullMethodName           = "/erebus.c2.ErebusC2/ExecuteTask"
	ErebusC2_GetTaskResult_FullMethodName         = "/erebus.c2.ErebusC2/GetTaskResult"
	ErebusC2_ListTasks_FullMethodName             = "/erebus.c2.ErebusC2/ListTasks"
	ErebusC2_Subscribe_FullMethodName             = "/erebus.c2.ErebusC2/Subscribe"
	ErebusC2_GenerateImplant_FullMethodName       = "/erebus.c2.ErebusC2/GenerateImplant"
	ErebusC2_RegisterImplantSecret_FullMethodName = "/erebus.c2.ErebusC2/RegisterImplantSecret"
	ErebusC2_ListLoot_FullMethodName              = "/erebus.c2.ErebusC2/ListLoot"
	ErebusC2_GetLoot_FullMethodName               = "/erebus.c2.ErebusC2/GetLoot"
	ErebusC2_ListPendingApprovals_FullMethodName  = "/erebus.c2.ErebusC2/ListPendingApprovals"
	ErebusC2_Approve_FullMethodName               = "/erebus.c2.ErebusC2/Approve"
	ErebusC2_Deny_FullMethodName                  = "/erebus.c2.ErebusC2/Deny"
)

// ErebusC2Client is the client API for ErebusC2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ErebusC2Client interface {
	// Listeners
	StartListener(ctx context.Context, in *StartListenerRequest, opts ...grpc.CallOption) (*StartListenerResponse, error)
	StopListener(ctx context.Context, in *StopListenerRequest, opts ...grpc.CallOption) (*StopListenerResponse, error)
	ListListeners(ctx context.Context, in *ListListenersRequest, opts ...grpc.CallOption) (*ListListenersResponse, error)
	// Sessions
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*KillSessionResponse, error)
	// Tasks
	ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error)
	GetTaskResult(ctx context.Context, in *GetTaskResultRequest, opts ...grpc.CallOption) (*GetTaskResultResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Events
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Builder
	GenerateImplant(ctx context.Context, in *GenerateImplantRequest, opts ...grpc.CallOption) (*GenerateImplantResponse, error)
	RegisterImplantSecret(ctx context.Context, in *RegisterImplantSecretRequest, opts ...grpc.CallOption) (*RegisterImplantSecretResponse, error)
	// Loot
	ListLoot(ctx context.Context, in *ListLootRequest, opts ...grpc.CallOption) (*ListLootResponse, error)
	GetLoot(ctx context.Context, in *GetLootRequest, opts ...grpc.CallOption) (*GetLootResponse, error)
	// Approval Gates
	ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListPendingApprovalsResponse, error)
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error)
	Deny(ctx context.Context, in *DenyRequest, opts ...grpc.CallOption) (*DenyResponse, error)
}

type erebusC2Client struct {
	cc grpc.ClientConnInterface
}

func NewErebusC2Client(cc grpc.ClientConnInterface) ErebusC2Client {
	return &erebusC2Client{cc}
}

func (c *erebusC2Client) StartListener(ctx context.Context, in *StartListenerRequest, opts ...grpc.CallOption) (*StartListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartListenerResponse)
	err := c.cc.Invoke(ctx, ErebusC2_StartListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) StopListener(ctx context.Context, in *StopListenerRequest, opts ...grpc.CallOption) (*StopListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopListenerResponse)
	err := c.cc.Invoke(ctx, ErebusC2_StopListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) ListListeners(ctx context.Context, in *ListListenersRequest, opts ...grpc.CallOption) (*ListListenersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListListenersResponse)
	err := c.cc.Invoke(ctx, ErebusC2_ListListeners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, ErebusC2_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, ErebusC2_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*KillSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillSessionResponse)
	err := c.cc.Invoke(ctx, ErebusC2_KillSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTaskResponse)
	err := c.cc.Invoke(ctx, ErebusC2_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) GetTaskResult(ctx context.Context, in *GetTaskResultRequest, opts ...grpc.CallOption) (*GetTaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResultResponse)
	err := c.cc.Invoke(ctx, ErebusC2_GetTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ErebusC2_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ErebusC2_ServiceDesc.Streams[0], ErebusC2_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ErebusC2_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *erebusC2Client) GenerateImplant(ctx context.Context, in *GenerateImplantRequest, opts ...grpc.CallOption) (*GenerateImplantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImplantResponse)
	err := c.cc.Invoke(ctx, ErebusC2_GenerateImplant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) RegisterImplantSecret(ctx context.Context, in *RegisterImplantSecretRequest, opts ...grpc.CallOption) (*RegisterImplantSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterImplantSecretResponse)
	err := c.cc.Invoke(ctx, ErebusC2_RegisterImplantSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) ListLoot(ctx context.Context, in *ListLootRequest, opts ...grpc.CallOption) (*ListLootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLootResponse)
	err := c.cc.Invoke(ctx, ErebusC2_ListLoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) GetLoot(ctx context.Context, in *GetLootRequest, opts ...grpc.CallOption) (*GetLootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLootResponse)
	err := c.cc.Invoke(ctx, ErebusC2_GetLoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...grpc.CallOption) (*ListPendingApprovalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingApprovalsResponse)
	err := c.cc.Invoke(ctx, ErebusC2_ListPendingApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveResponse)
	err := c.cc.Invoke(ctx, ErebusC2_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *erebusC2Client) Deny(ctx context.Context, in *DenyRequest, opts ...grpc.CallOption) (*DenyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyResponse)
	err := c.cc.Invoke(ctx, ErebusC2_Deny_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ErebusC2Server is the server API for ErebusC2 service.
// All implementations must embed UnimplementedErebusC2Server
// for forward compatibility.
type ErebusC2Server interface {
	// Listeners
	StartListener(context.Context, *StartListenerRequest) (*StartListenerResponse, error)
	StopListener(context.Context, *StopListenerRequest) (*StopListenerResponse, error)
	ListListeners(context.Context, *ListListenersRequest) (*ListListenersResponse, error)
	// Sessions
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	KillSession(context.Context, *KillSessionRequest) (*KillSessionResponse, error)
	// Tasks
	ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error)
	GetTaskResult(context.Context, *GetTaskResultRequest) (*GetTaskResultResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Events
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// Builder
	GenerateImplant(context.Context, *GenerateImplantRequest) (*GenerateImplantResponse, error)
	RegisterImplantSecret(context.Context, *RegisterImplantSecretRequest) (*RegisterImplantSecretResponse, error)
	// Loot
	ListLoot(context.Context, *ListLootRequest) (*ListLootResponse, error)
	GetLoot(context.Context, *GetLootRequest) (*GetLootResponse, error)
	// Approval Gates
	ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error)
	Approve(context.Context, *ApproveRequest) (*ApproveResponse, error)
	Deny(context.Context, *DenyRequest) (*DenyResponse, error)
	mustEmbedUnimplementedErebusC2Server()
}

// UnimplementedErebusC2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedErebusC2Server struct{}

func (UnimplementedErebusC2Server) StartListener(context.Context, *StartListenerRequest) (*StartListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartListener not implemented")
}
func (UnimplementedErebusC2Server) StopListener(context.Context, *StopListenerRequest) (*StopListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopListener not implemented")
}
func (UnimplementedErebusC2Server) ListListeners(context.Context, *ListListenersRequest) (*ListListenersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListListeners not implemented")
}
func (UnimplementedErebusC2Server) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedErebusC2Server) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedErebusC2Server) KillSession(context.Context, *KillSessionRequest) (*KillSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillSession not implemented")
}
func (UnimplementedErebusC2Server) ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedErebusC2Server) GetTaskResult(context.Context, *GetTaskResultRequest) (*GetTaskResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskResult not implemented")
}
func (UnimplementedErebusC2Server) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedErebusC2Server) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedErebusC2Server) GenerateImplant(context.Context, *GenerateImplantRequest) (*GenerateImplantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateImplant not implemented")
}
func (UnimplementedErebusC2Server) RegisterImplantSecret(context.Context, *RegisterImplantSecretRequest) (*RegisterImplantSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterImplantSecret not implemented")
}
func (UnimplementedErebusC2Server) ListLoot(context.Context, *ListLootRequest) (*ListLootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoot not implemented")
}
func (UnimplementedErebusC2Server) GetLoot(context.Context, *GetLootRequest) (*GetLootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoot not implemented")
}
func (UnimplementedErebusC2Server) ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingApprovals not implemented")
}
func (UnimplementedErebusC2Server) Approve(context.Context, *ApproveRequest) (*ApproveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedErebusC2Server) Deny(context.Context, *DenyRequest) (*DenyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deny not implemented")
}
func (UnimplementedErebusC2Server) mustEmbedUnimplementedErebusC2Server() {}
func (UnimplementedErebusC2Server) testEmbeddedByValue()                  {}

// UnsafeErebusC2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ErebusC2Server will
// result in compilation errors.
type UnsafeErebusC2Server interface {
	mustEmbedUnimplementedErebusC2Server()
}

func RegisterErebusC2Server(s grpc.ServiceRegistrar, srv ErebusC2Server) {
	// If the following call panics, it indicates UnimplementedErebusC2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ErebusC2_ServiceDesc, srv)
}

func _ErebusC2_StartListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).StartListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_StartListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).StartListener(ctx, req.(*StartListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_StopListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).StopListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_StopListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).StopListener(ctx, req.(*StopListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_ListListeners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListListenersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).ListListeners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_ListListeners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).ListListeners(ctx, req.(*ListListenersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_KillSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).KillSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_KillSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).KillSession(ctx, req.(*KillSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).ExecuteTask(ctx, req.(*ExecuteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_GetTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).GetTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_GetTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).GetTaskResult(ctx, req.(*GetTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ErebusC2Server).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ErebusC2_SubscribeServer = grpc.ServerStreamingServer[Event]

func _ErebusC2_GenerateImplant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateImplantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).GenerateImplant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_GenerateImplant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).GenerateImplant(ctx, req.(*GenerateImplantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_RegisterImplantSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterImplantSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).RegisterImplantSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_RegisterImplantSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).RegisterImplantSecret(ctx, req.(*RegisterImplantSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_ListLoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).ListLoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_ListLoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).ListLoot(ctx, req.(*ListLootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_GetLoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).GetLoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_GetLoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).GetLoot(ctx, req.(*GetLootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_ListPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingApprovalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).ListPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_ListPendingApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).ListPendingApprovals(ctx, req.(*ListPendingApprovalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ErebusC2_Deny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErebusC2Server).Deny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErebusC2_Deny_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErebusC2Server).Deny(ctx, req.(*DenyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ErebusC2_ServiceDesc is the grpc.ServiceDesc for ErebusC2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ErebusC2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "erebus.c2.ErebusC2",
	HandlerType: (*ErebusC2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartListener",
			Handler:    _ErebusC2_StartListener_Handler,
		},
		{
			MethodName: "StopListener",
			Handler:    _ErebusC2_StopListener_Handler,
		},
		{
			MethodName: "ListListeners",
			Handler:    _ErebusC2_ListListeners_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _ErebusC2_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _ErebusC2_GetSession_Handler,
		},
		{
			MethodName: "KillSession",
			Handler:    _ErebusC2_KillSession_Handler,
		},
		{
			MethodName: "ExecuteTask",
			Handler:    _ErebusC2_ExecuteTask_Handler,
		},
		{
			MethodName: "GetTaskResult",
			Handler:    _ErebusC2_GetTaskResult_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ErebusC2_ListTasks_Handler,
		},
		{
			MethodName: "GenerateImplant",
			Handler:    _ErebusC2_GenerateImplant_Handler,
		},
		{
			MethodName: "RegisterImplantSecret",
			Handler:    _ErebusC2_RegisterImplantSecret_Handler,
		},
		{
			MethodName: "ListLoot",
			Handler:    _ErebusC2_ListLoot_Handler,
		},
		{
			MethodName: "GetLoot",
			Handler:    _ErebusC2_GetLoot_Handler,
		},
		{
			MethodName: "ListPendingApprovals",
			Handler:    _ErebusC2_ListPendingApprovals_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _ErebusC2_Approve_Handler,
		},
		{
			MethodName: "Deny",
			Handler:    _ErebusC2_Deny_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ErebusC2_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
