// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: listener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenerProtocol int32

const (
	ListenerProtocol_LISTENER_UNKNOWN ListenerProtocol = 0
	ListenerProtocol_LISTENER_HTTPS   ListenerProtocol = 1
	ListenerProtocol_LISTENER_MTLS    ListenerProtocol = 2
	ListenerProtocol_LISTENER_DNS     ListenerProtocol = 3
)

// Enum value maps for ListenerProtocol.
var (
	ListenerProtocol_name = map[int32]string{
		0: "LISTENER_UNKNOWN",
		1: "LISTENER_HTTPS",
		2: "LISTENER_MTLS",
		3: "LISTENER_DNS",
	}
	ListenerProtocol_value = map[string]int32{
		"LISTENER_UNKNOWN": 0,
		"LISTENER_HTTPS":   1,
		"LISTENER_MTLS":    2,
		"LISTENER_DNS":     3,
	}
)

func (x ListenerProtocol) Enum() *ListenerProtocol {
	p := new(ListenerProtocol)
	*p = x
	return p
}

func (x ListenerProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenerProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_listener_proto_enumTypes[0].Descriptor()
}

func (ListenerProtocol) Type() protoreflect.EnumType {
	return &file_listener_proto_enumTypes[0]
}

func (x ListenerProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenerProtocol.Descriptor instead.
func (ListenerProtocol) EnumDescriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{0}
}

type ListenerConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol ListenerProtocol       `protobuf:"varint,3,opt,name=protocol,proto3,enum=erebus.c2.ListenerProtocol" json:"protocol,omitempty"`
	Host     string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port     uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	// TLS
	CertPath string `protobuf:"bytes,6,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath  string `protobuf:"bytes,7,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	// DNS specific
	Domain string `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	// Domain fronting
	CdnDomain     string `protobuf:"bytes,9,opt,name=cdn_domain,json=cdnDomain,proto3" json:"cdn_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerConfig) Reset() {
	*x = ListenerConfig{}
	mi := &file_listener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerConfig) ProtoMessage() {}

func (x *ListenerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerConfig.ProtoReflect.Descriptor instead.
func (*ListenerConfig) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListenerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListenerConfig) GetProtocol() ListenerProtocol {
	if x != nil {
		return x.Protocol
	}
	return ListenerProtocol_LISTENER_UNKNOWN
}

func (x *ListenerConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ListenerConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListenerConfig) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *ListenerConfig) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *ListenerConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListenerConfig) GetCdnDomain() string {
	if x != nil {
		return x.CdnDomain
	}
	return ""
}

type ListenerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      ListenerProtocol       `protobuf:"varint,3,opt,name=protocol,proto3,enum=erebus.c2.ListenerProtocol" json:"protocol,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerStatus) Reset() {
	*x = ListenerStatus{}
	mi := &file_listener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerStatus) ProtoMessage() {}

func (x *ListenerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerStatus.ProtoReflect.Descriptor instead.
func (*ListenerStatus) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{1}
}

func (x *ListenerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListenerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListenerStatus) GetProtocol() ListenerProtocol {
	if x != nil {
		return x.Protocol
	}
	return ListenerProtocol_LISTENER_UNKNOWN
}

func (x *ListenerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListenerStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ListenerStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

var File_listener_proto protoreflect.FileDescriptor

const file_listener_proto_rawDesc = "" +
	"\n" +
	"\x0elistener.proto\x12\terebus.c2\"\x84\x02\n" +
	"\x0eListenerConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x1b.erebus.c2.ListenerProtocolR\bprotocol\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x1b\n" +
	"\tcert_path\x18\x06 \x01(\tR\bcertPath\x12\x19\n" +
	"\bkey_path\x18\a \x01(\tR\akeyPath\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"cdn_domain\x18\t \x01(\tR\tcdnDomain\"\xbe\x01\n" +
	"\x0eListenerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x1b.erebus.c2.ListenerProtocolR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt*a\n" +
	"\x10ListenerProtocol\x12\x14\n" +
	"\x10LISTENER_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eLISTENER_HTTPS\x10\x01\x12\x11\n" +
	"\rLISTENER_MTLS\x10\x02\x12\x10\n" +
	"\fLISTENER_DNS\x10\x03B5Z3github.com/KKingZero/erebus-exploit-framwork/pkg/pbb\x06proto3"

var (
	file_listener_proto_rawDescOnce sync.Once
	file_listener_proto_rawDescData []byte
)

func file_listener_proto_rawDescGZIP() []byte {
	file_listener_proto_rawDescOnce.Do(func() {
		file_listener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listener_proto_rawDesc), len(file_listener_proto_rawDesc)))
	})
	return file_listener_proto_rawDescData
}

var file_listener_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_listener_proto_goTypes = []any{
	(ListenerProtocol)(0),  // 0: erebus.c2.ListenerProtocol
	(*ListenerConfig)(nil), // 1: erebus.c2.ListenerConfig
	(*ListenerStatus)(nil), // 2: erebus.c2.ListenerStatus
}
var file_listener_proto_depIdxs = []int32{
	0, // 0: erebus.c2.ListenerConfig.protocol:type_name -> erebus.c2.ListenerProtocol
	0, // 1: erebus.c2.ListenerStatus.protocol:type_name -> erebus.c2.ListenerProtocol
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_listener_proto_init() }
func file_listener_proto_init() {
	if File_listener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listener_proto_rawDesc), len(file_listener_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listener_proto_goTypes,
		DependencyIndexes: file_listener_proto_depIdxs,
		EnumInfos:         file_listener_proto_enumTypes,
		MessageInfos:      file_listener_proto_msgTypes,
	}.Build()
	File_listener_proto = out.File
	file_listener_proto_goTypes = nil
	file_listener_proto_depIdxs = nil
}
